name: opentofu publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'opentofu.portable/**'

jobs:
  Test-opentofu-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ¦º Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack opentofu.portable/opentofu.portable.nuspec
      - name: ğŸš€ Install Chocolatey Package
        run: choco install opentofu.portable -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"
      - name: ğŸš¨ Test opentofu
        run: tofu version
  Publish-opentofu-Package:
    runs-on: windows-latest
    needs: Test-opentofu-Package
    steps:
      - run: echo 'The triggering workflow passed'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack opentofu.portable/opentofu.portable.nuspec
      - name: ğŸ” Set Chocolatey API-KEY
        run: choco apikey --api-key ${{ secrets.API_KEY }} -source https://push.chocolatey.org/
      - name: ğŸš€ Push Chocolatey Package
        run: choco push -source https://push.chocolatey.org/