name: sharefile-for-windows publish
on:
  workflow_run:
    workflows: [sharefile-for-windows test]
    types: [completed]
run-name: ${{ github.event.workflow_run.name }}

jobs:
  on-success:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack sharefile-for-windows/sharefile-for-windows.nuspec --version 23.10.16.0
      - name: ğŸ” Set Chocolatey API-KEY
        run: choco apikey --api-key ${{ secrets.API_KEY }} -source https://push.chocolatey.org/
      - name: ğŸš€ Push Chocolatey Package
        run: choco push -source https://push.chocolatey.org/
  on-failure:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
