name: sharefile-for-windows publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'ShareFile-For-Windows/**'

jobs:
  Test-sharefile-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ¦º Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack ShareFile-For-Windows/ShareFile-For-Windows.nuspec
      - name: ğŸš€ Install Chocolatey Package
        run: choco install sharefile-for-windows -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"
  Publish-sharefile-Package:
    runs-on: windows-latest
    needs: Test-sharefile-Package
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack sharefile-for-windows/sharefile-for-windows.nuspec
      - name: ğŸ” Set Chocolatey API-KEY
        run: choco apikey --api-key ${{ secrets.API_KEY }} -source https://push.chocolatey.org/
      - name: ğŸš€ Push Chocolatey Package
        run: choco push -source https://push.chocolatey.org/