name: Zoom VDI plugin publish
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'Zoom-VDI-Universal-Plugin/**'

jobs:
  Test-zoom-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ¦º Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack Zoom-VDI-Universal-Plugin/zoom-vdi-universal-plugin.nuspec
      - name: ğŸš€ Install Chocolatey Package
        run: choco install zoom-vdi-universal-plugin -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"
  Publish-zoom-Package:
    runs-on: windows-latest
    needs: Test-zoom-Package
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: ğŸ“¦ Pack Chocolatey Package
        run: choco pack Zoom-VDI-Universal-Plugin/zoom-vdi-universal-plugin.nuspec
      - name: ğŸ” Set Chocolatey API-KEY
        run: choco apikey --api-key ${{ secrets.API_KEY }} -source https://push.chocolatey.org/
      - name: ğŸš€ Push Chocolatey Package
        run: choco push -source https://push.chocolatey.org/